In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('ventasTransformed.csv')

In [16]:
print(df.columns.tolist())
print(df.shape)

df.head()

['CantidadProducto3', 'ClienteDireccion', 'ClienteEdad', 'ClienteNombre', 'ClienteTelefono', 'ClienteGenero', 'ClienteMail', 'CantidadProducto2', 'CantidadProducto1', 'Año', 'DiaNomrbe', 'DiaSemana', 'DescuentoVenta', 'Año.1', 'Trimestre', 'Mes', 'Día', 'HoraVenta', 'MarcaProducto1', 'MarcaProducto2', 'MarcaProducto3', 'Mes.1', 'MesNombre', 'MetodoPago', 'NombreProducto1', 'NombreProducto2', 'NombreProducto3', 'PrecioUnitarioProducto2', 'PrecioUnitarioProducto3', 'SubtotalProducto1', 'SubtotalProducto2', 'SubtotalProducto3', 'SucursalCiudad', 'SucursalNombre', 'TotalVenta', 'VendedorNombre', 'VentaID', 'Trimestre.1', 'PrecioUnitarioProducto1']
(30000, 39)

,CantidadProducto3,ClienteDireccion,ClienteEdad,ClienteNombre,ClienteTelefono,ClienteGenero,ClienteMail,CantidadProducto2,CantidadProducto1,Año,...,SubtotalProducto1,SubtotalProducto2,SubtotalProducto3,SucursalCiudad,SucursalNombre,TotalVenta,VendedorNombre,VentaID,Trimestre.1,PrecioUnitarioProducto1
0,0,cll 1 #16-16,33,Alberto Arranz Cepeda,'+34 803219872,M,alberto95@yahoo.com,20,1,2020,...,4000000,112000000,0,No Especificado,Techcore Bogotá#2,144400000,Edu Juan Pedraza,18789,3,4000000
1,0,cll 1 #17-12,27,Albino Nieto Reguera,'+34 963623818,M,albino50@gmail.com,10,1,2018,...,4800000,30000000,0,Bogotá,Techcore Bogotá#2,78000000,Eloísa Plaza Hurtado,362,1,4800000
2,0,cll 1 #17-22,46,Liliana Revilla Corral,'+34 925 12 68 86,F,liliana83@yahoo.com,0,1,2018,...,6800000,0,0,Medellín,Techcore Medellín#2,64600000,Luisina Lasa,5442,3,6800000
3,0,cll 1 #20-84,27,Tiburcio Alcalde Sáez,'+34937 34 97 80,M,tiburcio35@gmail.com,0,1,2018,...,4400000,0,0,Cali,Techcore Cali,37400000,Florencio Iker Vara Nebot,9576,2,4400000
4,0,cll 1 #20-84,27,Tiburcio Alcalde Sáez,'+34937 34 97 80,M,tiburcio35@gmail.com,0,2,2023,...,13600000,0,0,Medellín,Techcore Medellín#1,136000000,Liliana Jordá Armengol,22240,1,6800000

In [24]:
clientes = (df[[
        'ClienteNombre',
        'ClienteGenero',
        'ClienteEdad',
        'ClienteMail',
        'ClienteTelefono',
        'ClienteDireccion']
].drop_duplicates().reset_index(drop=True))    
clientes['ClienteID'] = clientes.index + 1
clientes = clientes[['ClienteID', 'ClienteNombre', 'ClienteGenero', 'ClienteEdad', 'ClienteMail', 'ClienteTelefono', 'ClienteDireccion']]

vendedores = (df[['VendedorNombre']]).drop_duplicates().reset_index(drop=True)
vendedores['VendedorID'] = vendedores.index + 1
vendedores = vendedores[['VendedorID', 'VendedorNombre']]

ciudades = df[
        'SucursalCiudad'
].unique()
ciudades = pd.DataFrame(ciudades, columns=['Ciudad'])
ciudades['CiudadID'] = ciudades.index + 1
ciudades = ciudades[['CiudadID', 'Ciudad']]

sucursales = (df[[
        'SucursalNombre',
        'SucursalCiudad'
]].drop_duplicates().reset_index(drop=True))
sucursales['SucursalID'] = sucursales.index + 1
sucursales = sucursales.merge(
    ciudades,
    left_on = 'SucursalCiudad',
    right_on = 'Ciudad',
    how = 'left'
)
sucursales = sucursales[['SucursalID', 'SucursalNombre', 'SucursalCiudad', 'CiudadID']]

MetodoPago = df['MetodoPago'].dropna().unique()
MetodoPago = pd.DataFrame(MetodoPago, columns=['MetodoPago'])
MetodoPago ['MetodoPagoID'] = MetodoPago.index + 1
MetodoPago = MetodoPago[['MetodoPagoID', 'MetodoPago']]

In [21]:
sucursales[sucursales['SucursalNombre'].duplicated(keep=False)]

    SucursalID       SucursalNombre  CiudadID
0            1    Techcore Bogotá#2         1
1            2    Techcore Bogotá#2         2
2            3  Techcore Medellín#2         3
3            4        Techcore Cali         4
4            5  Techcore Medellín#1         3
5            6     Techcore Pereira         5
6            7    Techcore Bogotá#1         2
7            8  Techcore Medellín#1         1
8            9     Techcore Pereira         1
9           10    Techcore Bogotá#1         1
10          11        Techcore Cali         1
11          12  Techcore Medellín#2         1

### Tabla Productos

In [25]:
productos = pd.DataFrame(columns = ['NombreProducto', 'MarcaProducto', 'Precio'])

for x in range(1, 4): 
    append_producto = pd.DataFrame(columns = ['NombreProducto', 'MarcaProducto', 'Precio'])
    append_producto['NombreProducto'] = df[f'NombreProducto{x}']
    append_producto['MarcaProducto'] = df[f'MarcaProducto{x}']
    append_producto['Precio'] = df[f'PrecioUnitarioProducto{x}']
    productos = pd.concat([productos, append_producto], ignore_index=True)


productos = productos.dropna(subset=['NombreProducto','MarcaProducto','Precio'])
productos = productos.drop_duplicates(['NombreProducto','MarcaProducto'])
productos['ProductoID'] = productos.index + 1
productos = productos[['ProductoID', 'NombreProducto', 'MarcaProducto', 'Precio']]

### Para crear la tabla de Facturas, debemos hacer un merge usando los ID que creamos hasta ahora.

In [39]:
facturas = df.copy()
facturas = facturas.groupby('VentaID', as_index=False).first()

facturas = facturas[[
    'VentaID',
    'ClienteNombre',
    'ClienteEdad',
    'ClienteGenero',
    'ClienteMail',
    'SucursalNombre',
    'SucursalCiudad',
    'VendedorNombre',
    'MetodoPago',
    'DescuentoVenta',
    'TotalVenta',
    'Año',
    'MesNombre',
    'Día'
]]

facturas = facturas.merge(
    clientes[['ClienteID', 'ClienteNombre', 'ClienteMail']],
    on=['ClienteNombre', 'ClienteMail'],
    how='left'
)

facturas = facturas.merge(
    vendedores[['VendedorID', 'VendedorNombre']],
    on='VendedorNombre',
    how='left'
)

facturas = facturas.merge(
    sucursales[['SucursalID', 'SucursalNombre', 'SucursalCiudad']],
    on=['SucursalNombre', 'SucursalCiudad'],
    how='left'
)

### Tabla Detalles

In [40]:
DetalleFacturas = pd.DataFrame(columns = ['VentaID', 'ProductoID', 'Cantidad', 'Subtotal'])

for i in range(1, 4):
    detalle_temp = df[['VentaID', f'NombreProducto{i}', f'MarcaProducto{i}', f'CantidadProducto{i}', f'SubtotalProducto{i}']]
    detalle_temp = detalle_temp.merge(productos, left_on=[f'NombreProducto{i}', f'MarcaProducto{i}'], right_on=['NombreProducto', 'MarcaProducto'], how='left')
    detalle_temp = detalle_temp[['VentaID', 'ProductoID', f'CantidadProducto{i}', f'SubtotalProducto{i}']]
    detalle_temp = detalle_temp.rename(columns={f'CantidadProducto{i}': 'Cantidad', f'SubtotalProducto{i}': 'Subtotal'})

    DetalleFacturas = pd.concat([DetalleFacturas, detalle_temp], ignore_index=True)

DetalleFacturas = DetalleFacturas.drop_duplicates(['VentaID','ProductoID'])


DetalleFacturas = DetalleFacturas.dropna().reset_index(drop=True)
DetalleFacturas['Cantidad'] = DetalleFacturas['Cantidad'].astype(int)
DetalleFacturas['Subtotal'] = DetalleFacturas['Subtotal'].astype(float)
DetalleFacturas['VentaID'] = DetalleFacturas['VentaID'].astype(int)
DetalleFacturas['ProductoID'] = DetalleFacturas['ProductoID'].astype(int)

DetalleFacturas.sort_values(by=['VentaID'], inplace=True)
DetalleFacturas.reset_index(drop=True, inplace=True)

#Creamos un ID para cada detalle

DetalleFacturas['DetalleID'] = DetalleFacturas.index + 1
DetalleFacturas = DetalleFacturas[['DetalleID', 'VentaID', 'ProductoID', 'Cantidad', 'Subtotal']]

## Exportamos a un archivo Excel

In [41]:
dataframes = [
    ciudades,
    sucursales,
    vendedores,
    clientes, 
    MetodoPago, 
    productos,
    facturas,
    DetalleFacturas
]

nombres_hojas = [
    'Ciudades', 
    'Sucursales', 
    'Vendedores',
    'Clientes',
    'MetodosPago',
    'Productos',
    'Facturas',
    'DetalleFacturas'
]

ruta_del_archivo = 'modeloVentas.xlsx'

with pd.ExcelWriter(ruta_del_archivo, engine='xlsxwriter') as writer:
    for nombre_hoja, df in zip(nombres_hojas, dataframes):
        df_export = df.copy()
        df_export = df_export.fillna({
            'ClienteNombre': '',
            'VendedorNombre': '',
            'SucursalNombre': ''
        })
        df_export.to_excel(writer, sheet_name=nombre_hoja, index=False)